/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package a.b.c.d {

    [Bindable]
    [RemoteClass(alias="a.b.c.d.TestModel")]
    public class TestModel extends TestModelBase {
    }
}